output_dir: outputs/r14/blackswan
train_data:
  video_path: data/blackswan.mp4
  prompt: "A black swan swimming in a pond with lush greenery in the background."
  n_sample_frames: 16
validation_data:
  prompts:
  - "A black swan swimming in a pond with lush greenery in the background, oil painting style."
  - "A majestic flamingo swimming in a pond with lush greenery in the background."
  video_length: 16
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
- "attn1"
- "attn2.to_q"
- "attn_temp"
- "swa_attn1"
checkpointing_steps: 1000
validation_steps: 500
