output_dir: outputs/r16/ref_sp1_cg0.25_h8
train_data:
  video_path: data/man-skiing.mp4
  prompt: a man is skiing
  n_sample_frames: 16
validation_data:
  prompts:
  - spider man is skiing on the beach, cartoon style
  - a man, wearing pink clothes, is skiing at sunset
  video_length: 16
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
- "attn1"
- "attn2.to_q"
- "attn_temp"
- "swa_attn1"
checkpointing_steps: 1000
validation_steps: 500
shift_pixel: 1
channel_gamma: 0.25
