output_dir: "./outputs/american-flag-in-wind"
train_data:
  video_path: "data/american-flag-in-wind.mp4"
  prompt: "An American flag on a flagpole moves in the wind."
  n_sample_frames: 8
  frame_rate: 1
validation_data:
  prompts:
    - "An American flag on a flagpole moves in the wind, expressionist style."
    - "A Canadian flag on a flagpole moves in the wind."
    - "An American flag on a flagpole moves in the wind with mountains in the background."
  video_length: 8
  frame_rate: 1
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
  - "attn1"
  - "attn2.to_q"
  - "attn_temp"
  - "swa_attn1"
checkpointing_steps: 1000
validation_steps: 100
