output_dir: "./outputs/butterfly"
train_data:
  video_path: "data/butterfly.mp4"
  prompt: "A butterfly with black and orange wings perches on a plant amidst a field of golden grass."
  n_sample_frames: 9
validation_data:
  prompts:
  - "A butterfly with black and orange wings perches on a plant amidst a field of golden grass, portrayed in a neon lights style."
  - "A dragonfly with shimmering wings perches on a plant amidst a field of golden grass."
  - "A butterfly with black and orange wings perches on a plant amidst a mystic forest with glowing flora."
  - "A polar bear BMX rider in full gear maneuvering his bike over a ramp in a futuristic cyberpunk city, surrounded by neon billboards."
  video_length: 9
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
  - "attn1"
  - "attn2.to_q"
  - "attn_temp"
  - "swa_attn1"
checkpointing_steps: 1000
validation_steps: 100