output_dir: "./outputs/crossing"
train_data:
  video_path: "data/crossing.mp4"
  prompt: "Two individuals crossing a street at a railway intersection with buildings in the background."
  n_sample_frames: 9
validation_data:
  prompts:
  - "Two individuals crossing a street at a railway intersection, Studio Ghibli style."
  - "Two robots crossing a street at a railway intersection with buildings in the background."
  - "Two individuals crossing a street with a lively carnival procession in the background, complete with floats and costumed dancers."
  - "Two animated characters from a classic video game crossing a pixelated street, with a digitalized cityscape in the background."
  video_length: 9
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
  - "attn1"
  - "attn2.to_q"
  - "attn_temp"
  - "swa_attn1"
checkpointing_steps: 1000
validation_steps: 100