output_dir: "./outputs/daytime-crowd"

train_data:
  video_path: "data/daytime-crowd.mp4"
  prompt: "People walking in a busy street, daytime."
  n_sample_frames: 16
validation_data:
  prompts:
    - "People walking in a busy street, daytime, minecraft style."
    - "People riding bicycles in a busy street, daytime."
    - "People walking in antarctica snow wilderness, daytime."
  video_length: 16
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
  - "attn1"
  - "attn2.to_q"
  - "attn_temp"
  - "swa_attn1"
checkpointing_steps: 1000
validation_steps: 100