output_dir: "./outputs/earth-full-view"

train_data:
  video_path: "data/earth-full-view.mp4"
  prompt: "Full view of the Earth as it moves slowly toward the sun."
  n_sample_frames: 16

validation_data:
  prompts:
    - "Full view of the Earth, made out of chocolate, as it moves slowly toward the sun."
    - "Full view of Mars as it moves slowly toward the sun."
    - "Full view of the Earth as it moves slowly through a fireworks display."
  video_length: 16
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
  - "attn1"
  - "attn2.to_q"
  - "attn_temp"
  - "swa_attn1"
checkpointing_steps: 1000
validation_steps: 100