output_dir: "./outputs/lotus"

train_data:
  video_path: "data/lotus.mp4"
  prompt: "A beautiful lotus in river water on a rainy day."
  n_sample_frames: 16

validation_data:
  prompts:
    - "A beautiful lotus in river water on a sunny day."
    - "A beautiful poppy flower in river water on a rainy day."
    - "A beautiful lotus with New York City in the background on a rainy day."
  video_length: 16
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
  - "attn1"
  - "attn2.to_q"
  - "attn_temp"
  - "swa_attn1"
checkpointing_steps: 1000
validation_steps: 100