output_dir: outputs/man-running

train_data:
  video_path: data/man-running.mp4
  prompt: a man is running
  n_sample_frames: 16

validation_data:
  prompts:
  - Stephen Curry is running in Time Square
  - a man is running, Van Gogh style
  - a man is running in New York City
  video_length: 16
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
  - "attn1"
  - "attn2.to_q"
  - "attn_temp"
  - "swa_attn1"
checkpointing_steps: 1000
validation_steps: 100