output_dir: "./outputs/object-boat"
train_data:
  video_path: "data/object-boat.mp4"
  prompt: "A fishing boat sails near the coast"
  n_sample_frames: 16
validation_data:
  prompts:
  - "A fishing boat sails near the coast, Chibi Animation style"
  - "A sleek yacht sails near the coast"
  - "A fishing boat sails on the tranquil surface of a moonlit lake, surrounded by towering mountains"
  - "A colorful paper boat sails on a reflective surface in a surreal dreamlike landscape with floating islands above"
  video_length: 16
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
  - "attn1"
  - "attn2.to_q"
  - "attn_temp"
  - "swa_attn1"
checkpointing_steps: 1000
validation_steps: 100