output_dir: "./outputs/wind-turbines-at-dusk"

train_data:
  video_path: "data/wind-turbines-at-dusk.mp4"
  prompt: "Wind turbines spin during dusk."
  n_sample_frames: 16

validation_data:
  prompts:
    - "Wind turbines spin during dusk, origami style."
    - "Solar panels spin during dusk."
    - "Wind turbines spin in an office surrounded by cubicles."
  video_length: 16
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
  - "attn1"
  - "attn2.to_q"
  - "attn_temp"
  - "swa_attn1"
checkpointing_steps: 1000
validation_steps: 100