output_dir: "./outputs/comparison/bmx-bumps"
train_data:
  video_path: "data/Comparison/bmx-bumps.mp4"
  prompt: "A BMX rider in full gear maneuvering their bike over a dirt ramp in a BMX track."
  n_sample_frames: 16
validation_data:
  prompts:
  - "A BMX rider in full gear maneuvering his bike over a dirt ramp in a night-time cityscape with skyscrapers in the background."
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
  - "attn1"
  - "attn2.to_q"
  - "attn_temp"
  - "swa_attn1"
checkpointing_steps: 1000
validation_steps: 100