output_dir: "./outputs/comparison/horsejump"
train_data:
  video_path: "data/Comparison/horsejump-high.mp4"
  prompt: "A rider on a horse jumping over an obstacle in an equestrian competition with a clear sky and other obstacles in the background."
  n_sample_frames: 16
validation_data:
  prompts:
  - "A rider on a horse jumping over an obstacle in an equestrian competition, rendered in Van Gogh style with swirling skies and vibrant colors."
  frame_rate: 2
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: true
  num_inv_steps: 50
max_train_steps: 500
updated_modules:
  - "attn1"
  - "attn2.to_q"
  - "attn_temp"
  - "swa_attn1"
checkpointing_steps: 1000
validation_steps: 100